use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :national_voter_file, NationalVoterFile.Endpoint,
  http: [port: {:system, "PORT"}],
  instrumenters: [Timber.PhoenixInstrumenter],
  url: [scheme: "https", host: "api.nationalvoterfile.org", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Configure your database
config :national_voter_file, NationalVoterFile.Repo,
  adapter: Ecto.Adapters.Postgres,
  loggers: [{Timber.Ecto, :log, [:info]}],
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true

# CORS allowed origins
config :national_voter_file, allowed_origins: [
  "http://nationalvoterfile.org",
  "http://www.nationalvoterfile.org",
  "https://nationalvoterfile.org",
  "https://www.nationalvoterfile.org"
]

config :guardian, Guardian,
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

# Timber logging
config :logger,
  level: :info,
  backends: [Timber.Logger]
config :timber, :transport, Timber.Transports.IODevice

config :sentry,
  environment_name: Mix.env || :prod

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :national_voter_file, NationalVoterFile.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :national_voter_file, NationalVoterFile.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :national_voter_file, NationalVoterFile.Endpoint, server: true
#
# You will also need to set the application root to `.` in order
# for the new static assets to be served after a hot upgrade:
#
#     config :national_voter_file, NationalVoterFile.Endpoint, root: "."
